# Generated by Django 2.1 on 2018-09-06 18:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180826_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['Name', 'id'], 'verbose_name': 'دسته', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CHILDS', to='blog.Category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=tinymce.models.HTMLField(verbose_name='متن پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='POSTS', to='blog.Category', verbose_name='دسته ها'),
        ),
    ]
