# Generated by Django 2.1 on 2018-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180906_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Categories',
            field=models.ManyToManyField(blank=True, related_name='POSTS', to='blog.Category', verbose_name='دسته ها'),
        ),
    ]
