# Generated by Django 2.1 on 2018-09-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180906_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CommenterEmail',
            field=models.EmailField(blank=True, help_text='برای ارتباط ما با شما لطفا پر شود', max_length=254, verbose_name='پست الکترونیکی شما'),
        ),
    ]
