# Generated by Django 2.1 on 2018-09-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_commenteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CommentTime',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='زمان نظر دادن'),
        ),
    ]
