# Generated by Django 2.1 on 2018-09-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180907_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='CommentTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان نظر دادن'),
        ),
    ]
