# Generated by Django 2.1 on 2018-09-07 09:51

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20180907_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True, verbose_name='عنوان اسلاید')),
                ('Body', tinymce.models.HTMLField(max_length=2000, null=True, verbose_name='متن اسلاید')),
                ('Link', models.URLField(null=True, verbose_name='لینک اسلاید')),
                ('Image', models.ImageField(upload_to=blog.models.user_path_for_slides, verbose_name='تصویر اسلاید')),
                ('Commiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SLIDES', to=settings.AUTH_USER_MODEL, verbose_name='اسلاید گذار')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='CommentStatus',
            field=models.CharField(choices=[('A', 'تایید شده'), ('N', 'تایید نشده'), ('D', 'رد شده')], default='A', max_length=1, verbose_name='وضعیت نظر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.user_path_for_posts, verbose_name='تصویر پست'),
        ),
    ]
