# Generated by Django 2.1 on 2018-09-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180907_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Publish',
            field=models.BooleanField(default=True, verbose_name='منتشر شده'),
        ),
    ]
